/// Flutter icons Ehealthicon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Ehealthicon
///      fonts:
///       - asset: fonts/Ehealthicon.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Ehealthicon {
  Ehealthicon._();

  static const _kFontFam = 'Ehealthicon';

  static const IconData clipboard = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData notifications_none = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData torso = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xe804, fontFamily: _kFontFam);
}
