/// Flutter icons EhealthIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EhealthIcons
///      fonts:
///       - asset: fonts/EhealthIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EhealthIcons {
  EhealthIcons._();

  static const _kFontFam = 'EhealthIcons';

  static const IconData beranda = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData pesanan = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData notifikasi = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData profil = const IconData(0xe803, fontFamily: _kFontFam);
}
